# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{shakespeare}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Paul Campbell"]
  s.date = %q{2010-01-04}
  s.email = %q{paul@rslw.com}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "README.md",
     "Rakefile",
     "app/controllers/admin/pages_controller.rb",
     "app/controllers/pages_controller.rb",
     "app/models/page.rb",
     "app/views/admin/pages/_form.html.erb",
     "app/views/admin/pages/edit.html.erb",
     "app/views/admin/pages/index.html.erb",
     "app/views/admin/pages/new.html.erb",
     "app/views/layouts/admin.html.erb",
     "app/views/pages/show.html.erb",
     "config/cucumber.yml",
     "config/routes.rb",
     "features/admin_pages.feature",
     "features/public_pages.feature",
     "features/step_definitions/page_steps.rb",
     "features/step_definitions/web_steps.rb",
     "features/support/env.rb",
     "features/support/paths.rb",
     "features/support/shakespeare_env.rb",
     "generators/definition.txt",
     "generators/shakespeare/USAGE",
     "generators/shakespeare/shakespeare_generator.rb",
     "generators/shakespeare/templates/20091230095600_create_pages.rb",
     "lib/shakespeare.rb",
     "lib/shakespeare/helpers.rb",
     "lib/shakespeare/settings.rb",
     "lib/shakespeare/shakespeare.rb",
     "lib/shakespeare/view_helpers.rb",
     "rails/init.rb",
     "rerun.txt",
     "shakespeare.gemspec",
     "spec/blueprints.rb",
     "spec/controllers/admin/pages_controller_spec.rb",
     "spec/database.yml",
     "spec/debug.log",
     "spec/helpers_spec.rb",
     "spec/models/page_spec.rb",
     "spec/schema.rb",
     "spec/shakespeare_generator_spec.rb",
     "spec/shakespeare_spec.rb",
     "spec/spec_helper.rb",
     "spec/view_helpers_spec.rb"
  ]
  s.homepage = %q{http://www.github.com/paulca/shakespeare}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A Rails drop in CMS.}
  s.test_files = [
    "spec/blueprints.rb",
     "spec/controllers/admin/pages_controller_spec.rb",
     "spec/helpers_spec.rb",
     "spec/models/page_spec.rb",
     "spec/schema.rb",
     "spec/shakespeare_generator_spec.rb",
     "spec/shakespeare_spec.rb",
     "spec/spec_helper.rb",
     "spec/view_helpers_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

