sqlite:
  :adapter: sqlite
  :database: vendor/plugins/shakespeare/test/shakespeare_plugin.sqlite.db

sqlite3:
  :adapter: sqlite3
  :dbfile: vendor/plugins/shakespeare/test/shakespeare_plugin.sqlite3.db

postgresql:
  :adapter: postgresql
  :username: postgres
  :password: postgres
  :database: shakespeare_plugin_test
  :min_messages: ERROR

mysql:
  :adapter: mysql
  :host: localhost
  :username: root
  :password:
  :database: shakespeare_plugin_test